### ISSUE TITLE
Campaign Editor

### ISSUE THREAD

**Issue by amjad-majid** [demtech-ai/.github#1]
## Summary

_The **[Campaign Editor](https://www.notion.so/demtech/Campaign-Editor-v1-c62ac02fbb4b463f9cc471839d5a7f69?pvs=4)** comprises a **[Default Sequential Workflow Panel](https://www.notion.so/demtech/Campaign-Editor-v1-c62ac02fbb4b463f9cc471839d5a7f69?pvs=4#826946765e6b40f78a25536cee6da45b)** for structuring stages, a **[Visual Design Window](https://www.notion.so/demtech/Campaign-Editor-v1-c62ac02fbb4b463f9cc471839d5a7f69?pvs=4#59223f4f29ea4f6d952f4e99bc5c3393)** for interactive design, and a **[Widget Toolbox](https://www.notion.so/demtech/Campaign-Editor-v1-c62ac02fbb4b463f9cc471839d5a7f69?pvs=4#60098aa9c0ad44348139558788c8d061)** for adding a variety of widgets, collectively providing a robust platform for building and customizing effective campaigns._

## Purpose

_Add a purpose, in brief_

## Features
- [ ] [Default Sequential Workflow Panel](https://www.notion.so/demtech/Campaign-Editor-v1-c62ac02fbb4b463f9cc471839d5a7f69?pvs=4#826946765e6b40f78a25536cee6da45b)
- [ ] [Visual Design Window](https://www.notion.so/demtech/Campaign-Editor-v1-c62ac02fbb4b463f9cc471839d5a7f69?pvs=4#59223f4f29ea4f6d952f4e99bc5c3393)
- [ ] [Widget Toolbox](https://www.notion.so/demtech/Campaign-Editor-v1-c62ac02fbb4b463f9cc471839d5a7f69?pvs=4#60098aa9c0ad44348139558788c8d061)
- [ ] [Stages](https://www.notion.so/demtech/Campaign-Editor-v1-c62ac02fbb4b463f9cc471839d5a7f69?pvs=4#d738c4d56bf2486faabcba416f6bd9cc)
- [ ] [Variants](https://www.notion.so/demtech/Campaign-Editor-v1-c62ac02fbb4b463f9cc471839d5a7f69?pvs=4#3d2000c312af48a995cdb1d084ac8cc8)
- [ ] [Widgets](https://www.notion.so/demtech/Campaign-Editor-v1-c62ac02fbb4b463f9cc471839d5a7f69?pvs=4#39d16116cd6f426e96a5f1190541ef1b)

_List the line items / stories that make up this epic_

- [ ] Add metadata for new campaign (title, description, featured image, tags)
- [ ] Add/edit/duplicate/delete stage
- [ ]  Add/edit/duplicate/delete variant
- [ ] Set Entry Conditions
- [ ] Set Exit Conditions
- [ ] Visual Design Window (widgets, content edit window, widget edit panel)
- [ ] Campaign preview (mobile, tablet, desktop)
