### ISSUE TITLE
Campaign Index

### ISSUE THREAD

**Issue by amjad-majid** [demtech-ai/.github#2]
## Summary

_The [Campaign Index with Filterable and Sortable Listings](https://www.notion.so/demtech/Campaign-Index-v1-35ff01ad49184eb8832e08a043264270?pvs=4) for administrators and campaigners provides a user-friendly interface with intuitive sorting, filtering, and action features, enabling effective campaign management and oversight._

## Purpose

_The [Campaign Index](https://www.notion.so/demtech/Campaign-Index-v1-35ff01ad49184eb8832e08a043264270?pvs=4) for administrators serves as a centralized hub, providing a comprehensive overview of campaigns with robust sorting, filtering, and actionable features for efficient campaign management._

## [Features](https://www.notion.so/demtech/Campaign-Index-v1-35ff01ad49184eb8832e08a043264270?pvs=4#e7c4f64d3b4d484e81c8ab437b278b24)

- [ ] Sortable Listings
- [ ] Column Headers 
    - [ ] Campaign title
    - [ ] Total Sign-up Count
    - [ ] Growth
    - [ ] Campaign status 
    - [ ] Campaign publish date (in a readable format)
    - [ ] Campaign tags
- [ ] Campaign Actions
    - [ ] Create new campaign
    - [ ] Edit existing campaign
    - [ ] Close existing campaign
    - [ ] Archive existing campaign
    - [ ] Mark campaign as victory
- [ ] Sorting
    - [ ] Search and Sort
- [ ] Filtering
    - [ ] Filter by Campaign Type
    - [ ] Filter by Campaign Status

## Stories

- [ ] Display campaigns with column headers
- [ ] Campaign search bar
- [ ] Campaign filter options (Campaign Type, Campaign Status)
- [ ] Campaign action buttons (create, edit, close, archive)
