### ISSUE TITLE
Create Campaign

### ISSUE THREAD

**Issue by amjad-majid** [demtech-ai/.github#4]
## Summary

_A Campaigner can create a campaign with the following fields, that are meta-data, and also viewable in certain citizen UI layouts. As a secondary step, a Campaigner can edit the campaign page content and layout with a visual builder._

## Features
- [ ] Campaign Title
    - [ ] Admin UI
    - [ ] Citizen UI
- [ ] Campaign Description
    - [ ] Admin UI
    - [ ] Citizen UI
- [ ] Decision maker
    - [ ] Admin UI
    - [ ] Citizen UI
- [ ] Campaign featured image with image optimization
    - [ ] Admin UI
    - [ ] Citizen UI
- [ ] Campaign slug
    - [ ] Admin UI
    - [ ] Citizen UI
- [ ] Campaign content
- [ ] Action types
- [ ] Preview campaign on web and mobile
- [ ] Publish campaign

## Stories

- [ ] Create campaign with core information (title, description, campaign slug, featured image)
- [ ] Add in Stages and variants for new campaign using campaign editor
- [ ] Design and edit campaign content using Campaign editor
- [ ] Add/configure action types (sign, share, donate)
- [ ] Preview campaign on web, tablet and mobile
- [ ] Publish campaign + display on Citizen frontend website
- [ ] Display campaign with core information (title, description, featured image) on Citizen Frontend
- [ ] Display campaign with core information (title, description, metadata, featured image) on Admin Dashboard
