### ISSUE TITLE
Action Types: petition sign, share, donate 

### ISSUE THREAD

**Issue by amjad-majid** [demtech-ai/.github#5]
## Summary

A citizen can sign, share and donate to a campaign. The three action types are set and configured in the campaign creation process through stages and variants. Stages set the order of action type and any additional screens in the campaign flow while variants allow for different versions of each action/screen for A/B testing, including multilingual versions for the same campaign.

## Features

- [ ] Sign Petition
    - [ ] Admin UI
    - [ ] Citizen UI

- [ ] Share
    - [ ] Admin UI
    - [ ] Citizen UI

- [ ] Donate
    - [ ] Admin UI
    - [ ] Citizen UI

## Stories

- [ ] Sign petition widget with customizable form fields for campaigners (Admin UI)
- [ ] Share widget with customizable form fields for campaigners (Admin UI)
- [ ] Donate widget with customizable form fields for campaigners (Admin UI)
- [ ] Sign petition form for citizens (Citizen UI)
- [ ] Share petition form for citizens (Citizen UI)
- [ ] Donate petition form for citizens (Citizen UI)
