### ISSUE TITLE
Mark Campaign as Victory, Archive, Closed

### ISSUE THREAD

**Issue by amjad-majid** [demtech-ai/.github#6]
## Summary

The Mark Campaign as Victory, Archive, Closed feature provides a robust system for acknowledging and managing campaign outcomes, offering flexibility and control to campaigners while ensuring transparent communication with users on the frontend Citizen website.

## Features
- [ ] Set States of a Campaign
- [ ] State: Victory
- [ ] State: Archive
- [ ] State: Closed

## Stories

- [ ] Campaigner marks Victory for running campaign and posts Victory content update 
- [ ] Campaigner archives campaign (visible to campaigners, but hidden from frontend Citizen website)
- [ ] Campaigner closes campaign
- [ ] Campaign reaches Victory status automatically after signatures reached
- [ ] Campaign is marked automatically closed after reaching Victory status
