### ISSUE TITLE
Custom Campaign Workflows + A/B Testing

### ISSUE THREAD

**Issue by amjad-majid** [demtech-ai/.github#7]
## Summary

Custom Campaign Workflows offer personalized user journeys, allowing for strategic design, while A/B Testing provides a data-driven approach to optimize campaign elements and enhance overall performance within the Campaign Editor. Both features contribute to the effectiveness and adaptability of campaigns, ensuring they meet specific goals and resonate with the target audience.

The Campaign Editor facilitates Custom Campaign Workflows and A/B Testing functionality as described:

## Features
- [ ] Admin UI - Basic IF ELSE operation for stages
- [ ] Citizen UI - seamless flow through the stages as defined in the Admin UI.
- [ ] A/B Testing - Admin UI - Create 2 variants 
- [ ] A/B Testing - Citizen UI - Citizen sees relevant variants on citizen frontend website

## Stories

- [ ] Campaigner creates stages of the campaign and chains stages to execute in certain order
- [ ] Basic If / Else operations for stages with Entry/Exit conditions
- [ ] Campaigner creates two variants
- [ ] Relevant variants for campaign displayed on citizen frontend website (based on conditional logic)
